name: node-test

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: running
      uses: actions/checkout@v3
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      run: |
        npm ci
        node runner
