name: nodetest

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: run
      run: |
        npm ci
        node assets/js/runner.js
