name: test3

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: make request
      id: request
      uses: fjogeleit/http-request-action@v1.9.2
      with:
        url: 'https://api.notion.com/v1/databases/6af2c5e769a6422488fdb001ded7e946/query'
        method: 'POST'
        contentType: 'application/json'
        bearerToken: ${{ secrets.NOTION_TOKEN}}
        customHeaders: '{"Notion-Version": "2021-08-16"}'
        data: '{"sorts": [{property: `time`, direction: `ascending`}], "page_size": "1"}'

    - name: show response
      run: |
        echo ${{ steps.request.outputs.response}}
        echo ${{ fromJson(steps.request.outputs.response)}}
