name: test3

on:
  workflow_dispatch:

jobs:
  fetch-events-from-notion:
    runs-on: ubuntu-latest
    steps:
    - name: make request
      id: request
      uses: fjogeleit/http-request-action@v1.9.2
      with:
        url: 'https://api.notion.com/v1/databases/6af2c5e769a6422488fdb001ded7e946/query'
        method: 'POST'
        contentType: 'application/json'
        bearerToken: ${{ secrets.NOTION_TOKEN}}
        customHeaders: '{"Notion-Version": "2021-08-16"}'
        data: '{"sorts": [{"property": "event time", "direction": "ascending"}], "page_size": 1}'

    - name: show response
      run: |
        echo ${{ steps.request.outputs.response}}
        echo ${{ fromJson(steps.request.outputs.response)}}
        
    - name: checkout repository
      uses: actions/checkout@v3
      
    - name: process json file in repo, assign to env var
      id: set_old
      run: |
        old = $(cat ./assets/js/data_events.json)
        old="${old//'%'/'%25'}"
        old="${old//$'\n'/'%0A'}"
        old="${old//$'\r'/'%0D'}"
        echo "::set-output name=packageJson::$old"
        
    - name: idk at this point lol
      run: |
        echo "${{fromJson(steps.set_old.outputs.packageJson)}}"